<a href="https://colab.research.google.com/github/Modupegiwa/MTN-Customer-Churn-Analysis-Q1-2025/blob/main/MTN_Nigeria_Customer_Churn_Analysis_(Q1_2025).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Connect to Google Drive

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

# Import Libraries

In [ ]:
import pandas as pd
import numpy as np

# Extract and Read Data

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/MTN/mtn_customer_churn.csv')
df.head()

,Customer ID,Full Name,Date of Purchase,Age,State,MTN Device,Gender,Satisfaction Rate,Customer Review,Customer Tenure in months,Subscription Plan,Unit Price,Number of Times Purchased,Total Revenue,Data Usage,Customer Churn Status,Reasons for Churn
0,CUST0001,Ngozi Berry,Jan-25,27,Kwara,4G Router,Male,2,Fair,2,165GB Monthly Plan,35000,19,665000,44.48,Yes,Relocation
1,CUST0002,Zainab Baker,Mar-25,16,Abuja (FCT),Mobile SIM Card,Female,2,Fair,22,12.5GB Monthly Plan,5500,12,66000,19.79,Yes,Better Offers from Competitors
2,CUST0003,Saidu Evans,Mar-25,21,Sokoto,5G Broadband Router,Male,1,Poor,60,150GB FUP Monthly Unlimited,20000,8,160000,9.64,No,NaN
3,CUST0003,Saidu Evans,Mar-25,21,Sokoto,Mobile SIM Card,Male,1,Poor,60,1GB+1.5mins Daily Plan,500,8,4000,197.05,No,NaN
4,CUST0003,Saidu Evans,Mar-25,21,Sokoto,Broadband MiFi,Male,1,Poor,60,30GB Monthly Broadband Plan,9000,15,135000,76.34,No,NaN

# Data Inspection

## Data Dimension

In [ ]:
df.shape

(974, 17)

## Column Names

In [ ]:
df.columns

Index(['Customer ID', 'Full Name', 'Date of Purchase', 'Age', 'State',
       'MTN Device', 'Gender', 'Satisfaction Rate', 'Customer Review',
       'Customer Tenure in months', 'Subscription Plan', 'Unit Price',
       'Number of Times Purchased', 'Total Revenue', 'Data Usage',
       'Customer Churn Status', 'Reasons for Churn'],
      dtype='object')

## Get Information about the Data

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 974 entries, 0 to 973
Data columns (total 17 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Customer ID                974 non-null    object
 1   Full Name                  974 non-null    object
 2   Date of Purchase           974 non-null    object
 3   Age                        974 non-null    int64
 4   State                      974 non-null    object
 5   MTN Device                 974 non-null    object
 6   Gender                     974 non-null    object
 7   Satisfaction Rate          974 non-null    int64
 8   Customer Review            974 non-null    object
 9   Customer Tenure in months  974 non-null    int64
 10  Subscription Plan          974 non-null    object
 11  Unit Price                 974 non-null    int64
 12  Number of Times Purchased  974 non-null    int64
 13  Total Revenue              974 non-null    int64
 14  Data Usage                 974 non-null    float64
 15  Customer Churn Status      974 non-null    object
 16  Reasons for Churn          284 non-null    object
dtypes: float64(1), int64(6), object(10)
memory usage: 129.5+ KB

# Data Cleaning

## Check for Missing Values

In [ ]:
missing = (df.isnull().sum()/len(df))*100

missing.sort_values(ascending=False)

Reasons for Churn            70.841889
Customer ID                   0.000000
Full Name                     0.000000
Age                           0.000000
Date of Purchase              0.000000
MTN Device                    0.000000
Gender                        0.000000
Satisfaction Rate             0.000000
State                         0.000000
Customer Review               0.000000
Customer Tenure in months     0.000000
Unit Price                    0.000000
Subscription Plan             0.000000
Number of Times Purchased     0.000000
Total Revenue                 0.000000
Data Usage                    0.000000
Customer Churn Status         0.000000
dtype: float64

### Replace missing values in the specific column

In [ ]:

df['Reasons for Churn'] = df['Reasons for Churn'].fillna('Active Customer')

## Check for Duplicate Rows

In [ ]:
df.drop_duplicates(inplace=True)

## Change Datatypes

In [ ]:
df["Date of Purchase"] = pd.to_datetime(
    df["Date of Purchase"],
    format="%b-%y"
)

## Remove spaces in text columns.

In [ ]:
text_columns = [
    "State",
    "MTN Device",
    "Gender",
    "Customer Review",
    "Subscription Plan",
    "Customer Churn Status",
    "Reasons for Churn"
]

for col in text_columns:
    df[col] = df[col].str.strip()

## Create Age Groups

In [ ]:
bins = [0, 24, 40, 60, 81]
labels = ["Gen Z (16-24)", "Millennials (25-40)", "Gen X (41-60)", "Seniors (61+)"]

df["Age Group"] = pd.cut(df["Age"], bins=bins, labels=labels, right=False)

## Create Customer Segment

In [ ]:
conditions = [
    (df["Customer Churn Status"] == "Yes"),  # Already left
    (df["Customer Tenure in months"] >= 24) & (df["Satisfaction Rate"] >= 4),  # Long-term & happy
    (df["Total Revenue"] >= df["Total Revenue"].median())  # High spenders
]

choices = [
    "Lost Customer",
    "Loyal Tier",
    "High Value"
]

df["Customer Segment"] = np.select(conditions, choices, default="Regular")

# Final Data Check

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 974 entries, 0 to 973
Data columns (total 19 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Customer ID                974 non-null    object
 1   Full Name                  974 non-null    object
 2   Date of Purchase           974 non-null    datetime64[ns]
 3   Age                        974 non-null    int64
 4   State                      974 non-null    object
 5   MTN Device                 974 non-null    object
 6   Gender                     974 non-null    object
 7   Satisfaction Rate          974 non-null    int64
 8   Customer Review            974 non-null    object
 9   Customer Tenure in months  974 non-null    int64
 10  Subscription Plan          974 non-null    object
 11  Unit Price                 974 non-null    int64
 12  Number of Times Purchased  974 non-null    int64
 13  Total Revenue              974 non-null    int64
 14  Data Usage                 974 non-null    float64
 15  Customer Churn Status      974 non-null    object
 16  Reasons for Churn          974 non-null    object
 17  Age Group                  974 non-null    category
 18  Customer Segment           974 non-null    object
dtypes: category(1), datetime64[ns](1), float64(1), int64(6), object(10)
memory usage: 138.2+ KB

In [ ]:
df.head()

,Customer ID,Full Name,Date of Purchase,Age,State,MTN Device,Gender,Satisfaction Rate,Customer Review,Customer Tenure in months,Subscription Plan,Unit Price,Number of Times Purchased,Total Revenue,Data Usage,Customer Churn Status,Reasons for Churn,Age Group,Customer Segment
0,CUST0001,Ngozi Berry,2025-01-01,27,Kwara,4G Router,Male,2,Fair,2,165GB Monthly Plan,35000,19,665000,44.48,Yes,Relocation,Millennials (25-40),Lost Customer
1,CUST0002,Zainab Baker,2025-03-01,16,Abuja (FCT),Mobile SIM Card,Female,2,Fair,22,12.5GB Monthly Plan,5500,12,66000,19.79,Yes,Better Offers from Competitors,Gen Z (16-24),Lost Customer
2,CUST0003,Saidu Evans,2025-03-01,21,Sokoto,5G Broadband Router,Male,1,Poor,60,150GB FUP Monthly Unlimited,20000,8,160000,9.64,No,Active Customer,Gen Z (16-24),High Value
3,CUST0003,Saidu Evans,2025-03-01,21,Sokoto,Mobile SIM Card,Male,1,Poor,60,1GB+1.5mins Daily Plan,500,8,4000,197.05,No,Active Customer,Gen Z (16-24),Regular
4,CUST0003,Saidu Evans,2025-03-01,21,Sokoto,Broadband MiFi,Male,1,Poor,60,30GB Monthly Broadband Plan,9000,15,135000,76.34,No,Active Customer,Gen Z (16-24),High Value

# Descriptive Statistics

In [ ]:
df.describe().T

,count,mean,min,25%,50%,75%,max,std
Date of Purchase,974,2025-01-30 15:32:53.716632576,2025-01-01 00:00:00,2025-01-01 00:00:00,2025-02-01 00:00:00,2025-03-01 00:00:00,2025-03-01 00:00:00,NaN
Age,974.0,48.043121,16.0,32.0,49.0,63.75,80.0,17.764307
Satisfaction Rate,974.0,2.947639,1.0,2.0,3.0,4.0,5.0,1.384219
Customer Tenure in months,974.0,31.422998,1.0,17.0,31.0,47.0,60.0,17.191256
Unit Price,974.0,19196.663244,350.0,5500.0,14500.0,24000.0,150000.0,25586.726985
Number of Times Purchased,974.0,10.564682,1.0,5.0,11.0,15.0,20.0,5.709427
Total Revenue,974.0,204669.609856,350.0,33000.0,108000.0,261000.0,3000000.0,324785.499316
Data Usage,974.0,99.304764,0.82,47.6375,103.33,149.6975,200.0,57.739511

In [ ]:
from google.colab import auth
import pandas_gbq

# 1. Authenticate your account (Click the link, log in, and grant permission)
auth.authenticate_user()

# 2. Define your Google Cloud details
project_id = 'mtn-nigeria-analysis'
dataset_id = 'mtn-nigeria-analysis.mtn_customerchurn'
table_id   = 'powerbi_live_table'
destination_table = f"{dataset_id}.{table_id}"

pandas_gbq.to_gbq(df, destination_table, project_id=project_id, if_exists='replace')

print(f"Success! Data pushed to {destination_table}")

100%|██████████| 1/1 [00:00<00:00, 9597.95it/s]

Success! Data pushed to mtn-nigeria-analysis.mtn_customerchurn.powerbi_live_table